pipeline {
    agent any

    parameters {
        choice(name: 'BROWSER', choices: ['CHROME','SAFARI','FIREFOX'], description: 'This is a choice parameter')
        choice(name: 'BUILDTOOL', choices: ['MAKE','MAVEN','JENKINS'], description: 'This is a choice parameter')
    }

    stages {
        stage('Build') {
            steps {
                echo "The build is done using ${params.BUILDTOOL} on ${params.BROWSER} browser"
            }
        }

        stage('Test') {
            steps {
                script {
                    echo "${params.BROWSER}"
                }
            }
        }

    }
}