pipeline {
    agent any

    parameters {
        string(name: 'PARAM_STRING', defaultValue: 'input_string_param', description: 'This is a string parameter')
        choice(name: 'BROWSER', choices: 'CHROME,SAFARI,FIREFOX', description: 'This is a choice parameter')
        choice(name: 'BUILDTOOL', choices: 'MAKE,MAVEN,JENKINS', description: 'This is a choice parameter')
    }

    stages {
        stage('Build') {
            steps {
                sh '''
                    echo "The build is done using ${params.BUILDTOOL} on ${params.BROWSER} browser"
                    sleep 5
                '''
            }
        }

        stage('Test') {
            steps {
                script {
                    echo "${params.PARAM_STRING}"
                }
            }
        }

    }
}